/**
 * DermaSense AI — Comprehensive Skin Disease Knowledge Base
 * 40+ medically defined conditions across all ICD-10 dermatological categories
 * Covers all Fitzpatrick skin types (I-VI) and all body regions
 */

export type SeverityLevel = 'Critical' | 'High' | 'Moderate' | 'Low' | 'None'
export type UrgencyLevel = 'Immediate' | 'Within 1 week' | 'Within 1 month' | 'Routine' | 'No action needed'

export interface DiseaseInfo {
  name: string
  icd10: string
  category: 'Malignant' | 'Pre-Malignant' | 'Benign' | 'Inflammatory' | 'Infectious' | 'Pigmentation' | 'Vascular' | 'Follicular' | 'Healthy'
  severity: SeverityLevel
  urgency: UrgencyLevel
  description: string
  commonBodyParts: string[]
  visualMarkers: string[]
  abcde: { asymmetry: boolean; border: boolean; color: boolean; diameter: boolean }
  symptoms: string[]
  treatments: string[]
  precautions: string[]
  specialists: string[]
  recurrenceRisk: 'High' | 'Medium' | 'Low' | 'None'
  contagious: boolean
}

export const DISEASE_DB: Record<string, DiseaseInfo> = {
  // ─── TIER 1: MALIGNANT / CRITICAL ─────────────────────────────────────────
  mel: {
    name: 'Melanoma',
    icd10: 'C43.9',
    category: 'Malignant',
    severity: 'Critical',
    urgency: 'Immediate',
    description: 'The most serious type of skin cancer, developing from melanocytes (pigment-producing cells). Can spread to other organs if not caught early. Early detection dramatically improves survival rates.',
    commonBodyParts: ['back', 'arm', 'leg', 'face', 'chest'],
    visualMarkers: ['Irregular border', 'Multiple colors (brown, black, red, white, blue)', 'Asymmetric shape', '>6mm diameter', 'Changing over time'],
    abcde: { asymmetry: true, border: true, color: true, diameter: true },
    symptoms: ['Irregular moles', 'Changing color or border', 'Asymmetric appearance', 'Bleeding or crusting', 'Darkening under nail'],
    treatments: ['Wide local excision', 'Sentinel lymph node biopsy', 'Immunotherapy (pembrolizumab)', 'Targeted therapy (BRAF inhibitors)', 'Radiation therapy (advanced)'],
    precautions: ['Daily broad-spectrum sunscreen SPF50+', 'Avoid tanning beds completely', 'Monthly self skin examination', 'Annual full body dermatology check', 'Protective clothing outdoors'],
    specialists: ['Dermatologist', 'Oncologist', 'Surgical Oncologist'],
    recurrenceRisk: 'High',
    contagious: false,
  },
  bcc: {
    name: 'Basal Cell Carcinoma',
    icd10: 'C44.91',
    category: 'Malignant',
    severity: 'Critical',
    urgency: 'Within 1 week',
    description: 'Most common skin cancer. Develops from basal cells in the deepest layer of epidermis. Rarely metastasizes but can cause significant local destruction if left untreated.',
    commonBodyParts: ['face', 'neck', 'scalp', 'arm', 'ear'],
    visualMarkers: ['Pearly or waxy bump', 'Rolled border', 'Visible blood vessels (telangiectasia)', 'Open sore that heals and returns', 'Flat scar-like lesion'],
    abcde: { asymmetry: false, border: true, color: false, diameter: false },
    symptoms: ['Pearlescent bump', 'Open non-healing sore', 'Shiny scar-like lesion', 'Pink growth with raised edges', 'Occasional bleeding'],
    treatments: ['Mohs micrographic surgery', 'Cryotherapy', 'Topical medications (imiquimod, 5-FU)', 'Photodynamic therapy', 'Radiation therapy'],
    precautions: ['Sun protection year-round', 'Check for new or changing lesions monthly', 'Seek early evaluation', 'Avoid UV radiation', 'Annual dermatology visits'],
    specialists: ['Dermatologist', 'Mohs Surgeon'],
    recurrenceRisk: 'Medium',
    contagious: false,
  },
  scc: {
    name: 'Squamous Cell Carcinoma',
    icd10: 'C44.92',
    category: 'Malignant',
    severity: 'Critical',
    urgency: 'Within 1 week',
    description: 'Second most common skin cancer, arising from squamous cells. Can metastasize, especially when located on lips, ears, or arising from scars. Sun damage is the primary cause.',
    commonBodyParts: ['face', 'hand', 'ear', 'scalp', 'arm', 'foot'],
    visualMarkers: ['Firm red nodule', 'Rough scaly patch', 'Central ulceration', 'Raised wartlike growth', 'Crusting or bleeding'],
    abcde: { asymmetry: true, border: true, color: false, diameter: true },
    symptoms: ['Firm red nodule or plaque', 'Rough scaly patch', 'Sore that does not heal', 'Wart-like growth', 'Crusting with bleeding'],
    treatments: ['Surgical excision', 'Mohs surgery', 'Radiation therapy', 'Electrodessiccation and curettage', 'Chemotherapy (metastatic)'],
    precautions: ['Protective clothing', 'SPF 50+ sunscreen', 'Avoid tanning', 'Regular skin checks', 'Treat precancerous lesions promptly'],
    specialists: ['Dermatologist', 'Oncologist'],
    recurrenceRisk: 'Medium',
    contagious: false,
  },
  akiec: {
    name: 'Actinic Keratosis / Bowen\'s Disease',
    icd10: 'L57.0',
    category: 'Pre-Malignant',
    severity: 'High',
    urgency: 'Within 1 month',
    description: 'Rough, scaly patch caused by years of sun exposure. Considered a precancerous lesion that can progress to squamous cell carcinoma if untreated.',
    commonBodyParts: ['face', 'scalp', 'arm', 'hand', 'ear'],
    visualMarkers: ['Rough, dry, scaly patch (1-2cm)', 'Flat to slightly raised patch on red base', 'Hard or wart-like surface', 'Itching or burning', 'Pink/red/brown coloration'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Rough scaly patches', 'Redness around lesion', 'Itching or burning sensation', 'Persistent dryness', 'Occasional bleeding when picked'],
    treatments: ['Cryotherapy (liquid nitrogen)', 'Topical 5-fluorouracil', 'Photodynamic therapy', 'Imiquimod cream', 'Curettage and electrodesiccation'],
    precautions: ['Year-round sun protection', 'Regular dermatologist monitoring', 'Vitamin A supplements (consult doctor)', 'Avoid UV exposure', 'Examine all sun-exposed areas'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'Medium',
    contagious: false,
  },
  mcc: {
    name: 'Merkel Cell Carcinoma',
    icd10: 'C44.029',
    category: 'Malignant',
    severity: 'Critical',
    urgency: 'Immediate',
    description: 'Rare and aggressive skin cancer arising from Merkel cells. Associated with UV exposure and Merkel cell polyomavirus. High metastasis rate.',
    commonBodyParts: ['face', 'neck', 'arm', 'scalp'],
    visualMarkers: ['Flesh-colored or bluish-red nodule', 'Fast growing', 'Painless', 'Shiny surface', 'Located on sun-exposed areas'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Fast-growing dome-shaped nodule', 'Painless lump', 'Skin colored or red-blue color', 'Enlarged lymph nodes nearby'],
    treatments: ['Surgical excision', 'Sentinel lymph node biopsy', 'Radiation therapy', 'Immunotherapy (avelumab, pembrolizumab)', 'Chemotherapy'],
    precautions: ['Aggressive early treatment critical', 'Regular follow-up imaging', 'Immune monitoring', 'Avoid immunosuppressive drugs if possible'],
    specialists: ['Oncologist', 'Surgical Oncologist', 'Radiation Oncologist'],
    recurrenceRisk: 'High',
    contagious: false,
  },

  // ─── TIER 2: PRE-MALIGNANT / HIGH RISK ────────────────────────────────────
  lm: {
    name: 'Lentigo Maligna',
    icd10: 'D03.9',
    category: 'Pre-Malignant',
    severity: 'High',
    urgency: 'Within 1 week',
    description: 'A type of melanoma in situ occurring on chronically sun-damaged skin. Grows slowly as a flat, tan to dark-brown macule, primarily on the face of older adults.',
    commonBodyParts: ['face', 'neck', 'scalp', 'arm'],
    visualMarkers: ['Flat brown-black macule', 'Irregular border', 'Slowly enlarging', 'Multiple shades of brown', 'Sun-damaged surrounding skin'],
    abcde: { asymmetry: true, border: true, color: true, diameter: true },
    symptoms: ['Slowly enlarging flat brown patch', 'Irregular shape', 'Multiple shades of tan/brown/dark brown', 'Located on face or neck'],
    treatments: ['Wide surgical excision', 'Mohs surgery', 'Imiquimod cream (non-surgical)', 'Radiation (inoperable cases)'],
    precautions: ['Immediate dermatology referral', 'Biopsy for definitive diagnosis', 'Sun avoidance', 'Annual monitoring of all skin'],
    specialists: ['Dermatologist', 'Mohs Surgeon'],
    recurrenceRisk: 'High',
    contagious: false,
  },
  atypnv: {
    name: 'Atypical / Dysplastic Nevus',
    icd10: 'D22.9',
    category: 'Pre-Malignant',
    severity: 'High',
    urgency: 'Within 1 month',
    description: 'Moles with abnormal features that may indicate increased risk for melanoma. Characterized by irregular borders, uneven pigment, and size >6mm.',
    commonBodyParts: ['back', 'chest', 'arm', 'leg'],
    visualMarkers: ['Irregular border (not smooth)', 'Uneven pigmentation', 'Size >6mm', 'Multiple colors (tan, brown, pink)', 'Flat and raised component'],
    abcde: { asymmetry: true, border: true, color: true, diameter: true },
    symptoms: ['Large mole >6mm', 'Irregular or fuzzy border', 'Multiple shades of color', 'May be itchy or tender'],
    treatments: ['Excisional biopsy if suspicious', 'Monitoring with dermoscopy', 'Photographic mapping'],
    precautions: ['Regular skin self-exams monthly', 'Annual dermatology visits', 'Document any changes', 'Strict sun protection'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'Medium',
    contagious: false,
  },

  // ─── TIER 3: BENIGN GROWTHS ────────────────────────────────────────────────
  nv: {
    name: 'Melanocytic Nevus (Mole)',
    icd10: 'D22.9',
    category: 'Benign',
    severity: 'Low',
    urgency: 'Routine',
    description: 'Common benign skin lesion composed of pigment-producing melanocytes. Most moles are harmless, but any changes in size, shape, or color should be evaluated.',
    commonBodyParts: ['back', 'arm', 'leg', 'face', 'chest'],
    visualMarkers: ['Round or oval shape', 'Even brown/black color', 'Well-defined smooth border', 'Generally symmetrical', 'Flat or slightly raised'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Well-defined pigmented lesion', 'Consistent color throughout', 'Stable size and shape', 'Generally painless'],
    treatments: ['Observation and monitoring', 'Surgical removal if suspicious or cosmetic concern', 'Dermoscopic evaluation'],
    precautions: ['Monthly self-examination', 'Annual dermatology check', 'Photograph and track all moles', 'Protect from sun exposure'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'Low',
    contagious: false,
  },
  bkl: {
    name: 'Seborrheic Keratosis',
    icd10: 'L82.1',
    category: 'Benign',
    severity: 'Low',
    urgency: 'Routine',
    description: 'Common benign skin growth that appears as a waxy, "stuck-on" growth. One of the most common noncancerous skin growths in older adults. Not caused by sun exposure.',
    commonBodyParts: ['back', 'chest', 'face', 'scalp', 'neck'],
    visualMarkers: ['Waxy "stuck on" appearance', 'Tan, brown, or black color', 'Rough or warty texture', 'Well-defined border', 'Flat or slightly raised'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Scaly waxy appearance', 'Itching (occasionally)', 'Stuck-on look', 'Variable size', 'Usually painless'],
    treatments: ['No treatment required for benign lesions', 'Cryotherapy (cosmetic removal)', 'Curettage', 'Laser treatment'],
    precautions: ['Consult doctor if sudden many appear (Leser-Trélat sign)', 'Biopsy if uncertain diagnosis'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'Low',
    contagious: false,
  },
  df: {
    name: 'Dermatofibroma',
    icd10: 'M8832/0',
    category: 'Benign',
    severity: 'Low',
    urgency: 'Routine',
    description: 'Common benign fibrous nodule in the skin, often arising after minor injury. Firm, slightly raised, and tends to dimple inward when pinched.',
    commonBodyParts: ['leg', 'arm', 'back'],
    visualMarkers: ['Small firm bump', 'Pink to light brown color', 'Dimples inward when pinched', 'Mostly painless', '0.5-1cm diameter'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Small firm nodule', 'Slight tenderness', 'Hyperpigmented center', 'Itching occasionally'],
    treatments: ['No treatment required', 'Surgical excision (cosmetic)', 'Cryotherapy (partial flattening)'],
    precautions: ['Monitor for any rapid change in size', 'Consult doctor if uncomfortable'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'Low',
    contagious: false,
  },
  sk: {
    name: 'Solar Lentigo (Age Spot)',
    icd10: 'L81.4',
    category: 'Benign',
    severity: 'Low',
    urgency: 'Routine',
    description: 'Flat brown macule caused by chronic sun exposure. Common in adults over 40 on sun-exposed areas. Also called liver spots or age spots.',
    commonBodyParts: ['face', 'hand', 'arm', 'chest'],
    visualMarkers: ['Flat brown well-defined macule', 'Sun-exposed areas', 'Even tan/brown color', 'Sharp uniform border', 'Multiple lesions common'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Flat brown spot', 'Multiple spots in sun-exposed areas', 'No symptoms — cosmetic concern only'],
    treatments: ['No treatment necessary medically', 'Topical lightening creams', 'Cryotherapy', 'Laser treatment', 'Chemical peel'],
    precautions: ['Sunscreen daily to prevent new spots', 'Biopsy if uncertain — can mimic lentigo maligna'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'Low',
    contagious: false,
  },
  ep: {
    name: 'Epidermal (Sebaceous) Cyst',
    icd10: 'L72.0',
    category: 'Benign',
    severity: 'Low',
    urgency: 'Routine',
    description: 'A slow-growing benign cyst under the skin, typically flesh-colored with a visible central punctum (pore). Contains keratin and may become inflamed.',
    commonBodyParts: ['face', 'back', 'neck', 'chest', 'scalp'],
    visualMarkers: ['Smooth dome-shaped lump', 'Central punctum (black dot)', 'Flesh-colored or white', 'Moveable under skin', 'May express cottage cheese material'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Soft moveable lump', 'Expresses foul-smelling material', 'May become red and tender when infected', 'Slow growing'],
    treatments: ['Leave alone if asymptomatic', 'Surgical excision (complete with sac)', 'Antibiotics if infected', 'Incision and drainage (infected)'],
    precautions: ['Do not squeeze — risk of rupture and infection', 'See doctor if red or painful'],
    specialists: ['Dermatologist', 'General Surgeon'],
    recurrenceRisk: 'Medium',
    contagious: false,
  },
  py: {
    name: 'Pyogenic Granuloma',
    icd10: 'L98.0',
    category: 'Benign',
    severity: 'Moderate',
    urgency: 'Within 1 month',
    description: 'Rapidly growing benign vascular lesion that bleeds easily. Common during pregnancy, after minor skin injuries, or on areas of chronic irritation.',
    commonBodyParts: ['face', 'arm', 'hand', 'leg', 'foot'],
    visualMarkers: ['Bright red moist papule', 'Bleeds easily with minimal trauma', 'Fast growing (weeks)', 'Pedunculated (on stalk)', 'Glistening surface'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Rapidly growing red nodule', 'Frequent bleeding', 'May be on gum/lip during pregnancy', 'Rarely painful'],
    treatments: ['Shave excision and electrocautery', 'Cryotherapy', 'Laser ablation', 'Topical timolol (small lesions)', 'Complete excision to prevent recurrence'],
    precautions: ['Keep clean and covered', 'See doctor promptly — bleeds heavily', 'Remove during pregnancy causes high recurrence'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'High',
    contagious: false,
  },

  // ─── TIER 4: INFLAMMATORY & AUTOIMMUNE ────────────────────────────────────
  pso: {
    name: 'Psoriasis',
    icd10: 'L40.0',
    category: 'Inflammatory',
    severity: 'Moderate',
    urgency: 'Within 1 month',
    description: 'Chronic autoimmune skin disease causing rapid skin cell buildup, resulting in scales and red patches. Can range from mild to severe, often with nail and joint involvement.',
    commonBodyParts: ['scalp', 'back', 'arm', 'leg', 'hand', 'chest'],
    visualMarkers: ['Silvery-white scaly plaques', 'Well-defined red border', 'Symmetric distribution', 'Elbow/knee predilection', 'Nail pitting or onycholysis'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Red patches with thick silvery scales', 'Dry cracked skin that may bleed', 'Itching, burning, or soreness', 'Nail changes', 'Joint pain (psoriatic arthritis)'],
    treatments: ['Topical corticosteroids', 'Vitamin D analogues (calcipotriol)', 'Phototherapy (UVB/PUVA)', 'Systemic agents (methotrexate, cyclosporine)', 'Biologics (adalimumab, secukinumab)'],
    precautions: ['Avoid trigger factors (stress, infection, certain medications)', 'Moisturize daily', 'Manage associated conditions (arthritis, metabolic syndrome)', 'Regular follow-up'],
    specialists: ['Dermatologist', 'Rheumatologist (if joints involved)'],
    recurrenceRisk: 'High',
    contagious: false,
  },
  ec: {
    name: 'Eczema / Atopic Dermatitis',
    icd10: 'L20.9',
    category: 'Inflammatory',
    severity: 'Moderate',
    urgency: 'Within 1 month',
    description: 'Common chronic inflammatory skin condition causing dry, itchy, inflamed skin. Often begins in childhood. Associated with asthma and allergic rhinitis (atopic triad).',
    commonBodyParts: ['arm', 'leg', 'hand', 'face', 'chest', 'foot'],
    visualMarkers: ['Dry itchy inflamed patches', 'Flexural distribution (elbow, knee creases)', 'Lichenification with chronic scratching', 'Weeping or crusting in acute phase', 'Excoriation marks'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Intense itching, especially at night', 'Dry cracked skin', 'Red to brownish-gray patches', 'Small raised bumps that may weep', 'Swollen irritated skin from scratching'],
    treatments: ['Emollients and moisturizers (cornerstone)', 'Topical corticosteroids (flares)', 'Topical calcineurin inhibitors (tacrolimus)', 'Dupilumab (biologic for severe cases)', 'Antihistamines for itch'],
    precautions: ['Daily moisturizing routine', 'Identify and avoid triggers', 'Use fragrance-free products', 'Avoid hot showers', 'Wet wrap therapy for children'],
    specialists: ['Dermatologist', 'Allergist/Immunologist'],
    recurrenceRisk: 'High',
    contagious: false,
  },
  ros: {
    name: 'Rosacea',
    icd10: 'L71.9',
    category: 'Inflammatory',
    severity: 'Moderate',
    urgency: 'Routine',
    description: 'Chronic facial skin condition causing redness, visible blood vessels, and sometimes acne-like bumps. Affects the central face and can involve the eyes.',
    commonBodyParts: ['face'],
    visualMarkers: ['Central facial redness (cheeks, nose, chin)', 'Visible broken blood vessels', 'Inflammatory papules and pustules', 'Skin thickening (rhinophyma in severe cases)', 'Eye involvement (ocular rosacea)'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Flushing and persistent redness', 'Visible blood vessels', 'Swollen red bumps', 'Eye problems (dryness/irritation)', 'Enlarged nose (in men, severe)'],
    treatments: ['Topical metronidazole or azelaic acid', 'Oral antibiotics (doxycycline)', 'Laser/IPL for vascular component', 'Ivermectin cream', 'Avoid triggers (sun, alcohol, spicy food)'],
    precautions: ['Daily SPF 30+ sunscreen', 'Avoid known triggers', 'Gentle skincare routine', 'No harsh scrubs', 'See ophthalmologist if eye symptoms'],
    specialists: ['Dermatologist', 'Ophthalmologist (if eye involvement)'],
    recurrenceRisk: 'High',
    contagious: false,
  },
  acne: {
    name: 'Acne Vulgaris',
    icd10: 'L70.0',
    category: 'Follicular',
    severity: 'Moderate',
    urgency: 'Routine',
    description: 'Common skin condition causing pimples, blackheads, and cysts when hair follicles become plugged with oil and dead skin cells. Affects mostly the face, back, and chest.',
    commonBodyParts: ['face', 'back', 'chest', 'neck', 'scalp'],
    visualMarkers: ['Blackheads (open comedones)', 'Whiteheads (closed comedones)', 'Inflammatory papules and pustules', 'Nodules and cysts (severe)', 'Scarring and hyperpigmentation'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Pimples and blackheads', 'Oily skin', 'Scarring', 'Tenderness and pain', 'Psychological distress'],
    treatments: ['Topical retinoids (tretinoin)', 'Benzoyl peroxide', 'Topical antibiotics (clindamycin)', 'Oral antibiotics (doxycycline)', 'Isotretinoin (severe acne)'],
    precautions: ['Gentle cleansing twice daily', 'Non-comedogenic products', 'Avoid picking or squeezing', 'Manage stress', 'Diet modification (low glycemic)'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'High',
    contagious: false,
  },
  lu: {
    name: 'Lupus (Discoid)',
    icd10: 'L93.0',
    category: 'Inflammatory',
    severity: 'High',
    urgency: 'Within 1 week',
    description: 'Chronic autoimmune skin disease where the immune system attacks skin cells. Can cause scarring, hyperpigmentation, and hair loss. May be associated with systemic lupus.',
    commonBodyParts: ['face', 'scalp', 'ear', 'neck'],
    visualMarkers: ['Butterfly (malar) rash on face', 'Disc-shaped scaly plaques', 'Scarring after healing', 'Photosensitive distribution', 'Hyperpigmented borders, hypopigmented center'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Butterfly-shaped rash across cheeks', 'Disc-shaped scalp lesions causing hair loss', 'Photosensitivity', 'Scarring', 'Joint pain (systemic involvement)'],
    treatments: ['Topical corticosteroids', 'Hydroxychloroquine', 'Sun protection (strict)', 'Tacrolimus ointment', 'Systemic treatment (if systemic lupus)'],
    precautions: ['Strict sun avoidance', 'Daily broad-spectrum sunscreen', 'Evaluate for systemic lupus (blood tests)', 'Monitor for organ involvement'],
    specialists: ['Dermatologist', 'Rheumatologist'],
    recurrenceRisk: 'High',
    contagious: false,
  },
  lp: {
    name: 'Lichen Planus',
    icd10: 'L43.9',
    category: 'Inflammatory',
    severity: 'Moderate',
    urgency: 'Within 1 month',
    description: 'Inflammatory condition affecting skin, nails, and mucous membranes. Characterized by purple flat-topped papules with Wickham\'s striae (white lacy lines).',
    commonBodyParts: ['arm', 'leg', 'back', 'scalp', 'neck'],
    visualMarkers: ['Purple/violet flat-topped polygonal papules', 'Wickham\'s striae (white lacy lines)', 'Intense itching', 'Flexural distribution', 'Linear pattern after scratching (Koebner)'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Itchy purple shiny bumps', 'White lacey patches in mouth', 'Painful mouth sores', 'Nail changes', 'Hair loss (scalp LP)'],
    treatments: ['Topical corticosteroids', 'Oral corticosteroids (widespread)', 'Topical calcineurin inhibitors (oral LP)', 'Retinoids', 'Light therapy (PUVA)'],
    precautions: ['Avoid aggravating medications', 'Gentle dental care for oral LP', 'Stress management', 'Monitor for oral malignant transformation'],
    specialists: ['Dermatologist', 'Dentist (oral LP)'],
    recurrenceRisk: 'Medium',
    contagious: false,
  },
  dc: {
    name: 'Dermatomyositis',
    icd10: 'M33.10',
    category: 'Inflammatory',
    severity: 'High',
    urgency: 'Within 1 week',
    description: 'Rare inflammatory disease causing muscle weakness and distinctive skin rashes. Associated with internal malignancy in adults. Requires systemic work-up.',
    commonBodyParts: ['face', 'chest', 'hand', 'back'],
    visualMarkers: ['Heliotrope rash (purple-red eyelid discoloration)', 'Gottron\'s papules on knuckles', 'Violet rash on chest (V-sign)', 'Mechanic\'s hands', 'Periungual telangiectasia'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Heliotrope periorbital rash', 'Muscle weakness (proximal)', 'Gottron\'s papules on knuckles', 'Difficulty climbing stairs or lifting', 'Dysphagia'],
    treatments: ['Systemic corticosteroids', 'Immunosuppressants (methotrexate, azathioprine)', 'IVIG', 'Hydroxychloroquine (skin)', 'Physical therapy'],
    precautions: ['Screen for malignancy (cancer workup)', 'Sun protection', 'Modify diet if swallowing difficulty', 'Cardiac and pulmonary monitoring'],
    specialists: ['Dermatologist', 'Rheumatologist', 'Neurologist'],
    recurrenceRisk: 'High',
    contagious: false,
  },
  bp: {
    name: 'Bullous Pemphigoid',
    icd10: 'L12.0',
    category: 'Inflammatory',
    severity: 'High',
    urgency: 'Within 1 week',
    description: 'Rare autoimmune blistering disorder causing large tense blisters on the skin. Most common in elderly patients. Autoantibodies target hemidesmosomes.',
    commonBodyParts: ['arm', 'leg', 'chest', 'abdomen'],
    visualMarkers: ['Large tense fluid-filled blisters', 'Surrounding normal or reddened skin', 'Blisters on trunk and limbs', 'Urticarial plaques before blisters', 'Mucous membranes spared usually'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Large tense blisters', 'Intense itching before blisters', 'Blisters on arms, legs, abdomen', 'Skin redness', 'Rarely mouth sores'],
    treatments: ['Topical superpotent corticosteroids', 'Systemic corticosteroids', 'Dapsone', 'Immunosuppressants', 'Rituximab (refractory)'],
    precautions: ['Gentle wound care for intact/broken blisters', 'Infection prevention', 'Fall prevention (elderly)', 'Monitor steroid side effects'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'High',
    contagious: false,
  },
  gr: {
    name: 'Granuloma Annulare',
    icd10: 'L92.0',
    category: 'Inflammatory',
    severity: 'Low',
    urgency: 'Routine',
    description: 'Benign self-limited inflammatory skin condition forming ring-shaped lesions. Typically affects hands and feet in young patients. Usually resolves spontaneously.',
    commonBodyParts: ['hand', 'arm', 'foot', 'leg'],
    visualMarkers: ['Ring-shaped or arcuate arrangement of papules', 'Red/purple/skin-colored', 'No scaling', 'Smooth surface', 'Center normal-appearing skin'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Ring-shaped lesions on hands/feet', 'Generally asymptomatic', 'Cosmetic concern primarily', 'Some mild itching'],
    treatments: ['Often self-resolves in 1-2 years', 'Topical corticosteroids (mild)', 'Intralesional corticosteroids', 'Cryotherapy', 'Light therapy (widespread)'],
    precautions: ['Evaluate for underlying diabetes (generalized form)', 'No urgent treatment needed for localized form'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'Medium',
    contagious: false,
  },

  // ─── TIER 5: INFECTIOUS ───────────────────────────────────────────────────
  imp: {
    name: 'Impetigo',
    icd10: 'L01.0',
    category: 'Infectious',
    severity: 'Moderate',
    urgency: 'Within 1 week',
    description: 'Highly contagious superficial bacterial skin infection, mainly caused by Staphylococcus aureus or Streptococcus pyogenes. Most common in young children.',
    commonBodyParts: ['face', 'arm', 'leg', 'hand'],
    visualMarkers: ['Honey-colored crusts on red base', 'Fluid-filled blisters (bullous form)', 'Occurs around nose and mouth in children', 'Spreading satellite lesions', 'Weeping eroded areas'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Honey-colored crusty sores', 'Itching', 'Pain in surrounding skin', 'Rapidly spreading', 'Swollen lymph nodes'],
    treatments: ['Topical mupirocin or fusidic acid (localized)', 'Oral antibiotics (widespread — cefalexin, flucloxacillin)', 'Warm water soaks to remove crusts', 'MRSA treatment if resistant'],
    precautions: ['Highly contagious — keep child home from school', 'Wash hands frequently', 'Avoid sharing towels', 'Keep lesions covered', 'Complete antibiotic course'],
    specialists: ['General Practitioner', 'Dermatologist'],
    recurrenceRisk: 'Medium',
    contagious: true,
  },
  cel: {
    name: 'Cellulitis',
    icd10: 'L03.90',
    category: 'Infectious',
    severity: 'High',
    urgency: 'Immediate',
    description: 'Acute bacterial infection of the deeper layers of the skin. Characterized by rapidly spreading redness, warmth, and swelling. Can lead to sepsis if untreated.',
    commonBodyParts: ['leg', 'arm', 'face', 'hand', 'foot'],
    visualMarkers: ['Hot red swollen skin', 'Poorly defined spreading border', 'Tenderness to touch', 'Fever and systemic symptoms', 'May show peau d\'orange texture'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Rapidly spreading warmth/redness', 'Swollen skin', 'Fever and chills', 'Tenderness and pain', 'Red streaking (lymphangitis)'],
    treatments: ['Oral antibiotics (cefalexin, amoxicillin-clavulanate)', 'IV antibiotics (hospitalization for severe cases)', 'Elevation of affected limb', 'Mark borders to monitor spread'],
    precautions: ['Seek immediate medical care if spreading', 'Monitor for red streaking/sepsis', 'Treat underlying conditions (diabetes, edema)', 'Complete antibiotic course'],
    specialists: ['General Practitioner', 'Infectious Disease Specialist'],
    recurrenceRisk: 'Medium',
    contagious: false,
  },
  hzv: {
    name: 'Herpes Zoster (Shingles)',
    icd10: 'B02.9',
    category: 'Infectious',
    severity: 'High',
    urgency: 'Within 1 week',
    description: 'Viral skin infection caused by reactivation of varicella-zoster virus (chickenpox virus). Causes painful dermatomal blister rash, and can cause lasting nerve pain (postherpetic neuralgia).',
    commonBodyParts: ['chest', 'abdomen', 'back', 'arm', 'face'],
    visualMarkers: ['Grouped vesicles on red base', 'Strictly one side of body (dermatomal)', 'Linear or band-like distribution', 'Preceded by pain/burning', 'Crusts after 7-10 days'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Burning pain before rash appears', 'Blistering rash on one side of body', 'Itching and tingling', 'Fever and fatigue', 'Persistent pain after rash (PHN)'],
    treatments: ['Antiviral medications (acyclovir, valacyclovir) — start within 72h', 'Pain management (analgesics, gabapentin)', 'Capsaicin patches for PHN', 'Vaccination (Shingrix) for prevention'],
    precautions: ['Start antivirals immediately — within 72 hours critical', 'Avoid contact with immunocompromised and unvaccinated', 'Pain management essential', 'Ophthalmologist if affects eye area'],
    specialists: ['General Practitioner', 'Dermatologist', 'Neurologist (PHN)'],
    recurrenceRisk: 'Low',
    contagious: true,
  },
  tca: {
    name: 'Tinea (Ringworm / Athlete\'s Foot)',
    icd10: 'B35.9',
    category: 'Infectious',
    severity: 'Moderate',
    urgency: 'Within 1 month',
    description: 'Fungal infection of the skin caused by dermatophytes. Various forms depending on location: tinea pedis (athlete\'s foot), tinea corporis (ringworm), tinea capitis (scalp).',
    commonBodyParts: ['foot', 'hand', 'arm', 'leg', 'scalp', 'chest'],
    visualMarkers: ['Ring-shaped scaly lesion with central clearing', 'Red raised border', 'Scaling and peeling', 'Interdigital maceration (foot)', 'Fluorescence under Wood\'s lamp (scalp)'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Circular scaly patch', 'Itching', 'Burning between toes', 'Cracked or blistered skin', 'Scalp: hair loss with scaling (children)'],
    treatments: ['Topical antifungals (clotrimazole, terbinafine) — 2-4 weeks', 'Oral antifungals (terbinafine, griseofulvin) for scalp/nails/extensive', 'Keep area dry', 'Treat affected contacts'],
    precautions: ['Keep skin dry — especially between toes', 'Avoid sharing towels/shoes', 'Wear breathable footwear', 'Treat pets with ringworm', 'Complete full treatment course'],
    specialists: ['General Practitioner', 'Dermatologist'],
    recurrenceRisk: 'Medium',
    contagious: true,
  },
  scb: {
    name: 'Scabies',
    icd10: 'B86',
    category: 'Infectious',
    severity: 'Moderate',
    urgency: 'Within 1 week',
    description: 'Highly contagious skin infestation by the mite Sarcoptes scabiei. Causes intense itching especially at night, with burrow tracks visible between fingers.',
    commonBodyParts: ['hand', 'arm', 'leg', 'chest', 'abdomen'],
    visualMarkers: ['Silvery burrow tracks (interdigital)', 'Intense nocturnal itch', 'Papules, vesicles, and pustules', 'Generalized rash', 'Excoriation marks'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Intense itching — worse at night', 'Burrow tracks between fingers', 'Rash on wrists, belt line, genitals', 'Itch before rash visible', 'Household members affected'],
    treatments: ['Topical permethrin 5% cream (all body below neck)', 'Oral ivermectin (alternative/severe)', 'Treat all household contacts simultaneously', 'Wash all bedding/clothing in hot water'],
    precautions: ['Treat entire household at same time', 'Machine wash/dry all clothing and bedding', 'Bag non-washable items for 72 hours', 'Avoid close skin contact until treated'],
    specialists: ['General Practitioner', 'Dermatologist'],
    recurrenceRisk: 'Medium',
    contagious: true,
  },
  mc: {
    name: 'Molluscum Contagiosum',
    icd10: 'B08.1',
    category: 'Infectious',
    severity: 'Low',
    urgency: 'Routine',
    description: 'Viral skin infection causing small pearly papules with central dimple (umbilication). Common in children and sexually active adults. Usually self-limiting.',
    commonBodyParts: ['face', 'arm', 'chest', 'abdomen', 'leg'],
    visualMarkers: ['Small pearlescent dome-shaped papules', 'Central umbilication (dimple)', '2-5mm diameter', 'Skin-colored or pink', 'Clusters or linear spread (from scratching)'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Small painless bumps', 'Mild itching', 'Spread by scratching', 'Usually asymptomatic'],
    treatments: ['Usually self-resolves in 6-12 months', 'Cryotherapy (cosmetic)', 'Curettage', 'Topical podophyllotoxin', 'Imiquimod cream'],
    precautions: ['Avoid sharing towels or touching lesions', 'Avoid scratching — prevents spread', 'Swimming pools — cover lesions', 'Sexual transmission possible in adults'],
    specialists: ['Dermatologist', 'General Practitioner'],
    recurrenceRisk: 'Low',
    contagious: true,
  },
  vr: {
    name: 'Verruca / Warts',
    icd10: 'B07.9',
    category: 'Infectious',
    severity: 'Low',
    urgency: 'Routine',
    description: 'Benign viral skin growths caused by human papillomavirus (HPV). Various types: common warts, plantar warts (foot), flat warts, and genital warts.',
    commonBodyParts: ['hand', 'foot', 'face', 'arm', 'leg'],
    visualMarkers: ['Rough hyperkeratotic papule', 'Black dots (thrombosed capillaries)', 'Multiple similar lesions', 'Flat smooth type (face)', 'Deep painful type on sole'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Rough grainy bump', 'Painful when walking (plantar)', 'Clusters', 'Small flesh-colored bumps'],
    treatments: ['Salicylic acid (topical, regular application)', 'Cryotherapy', 'Laser treatment', 'Immunotherapy (imiquimod)', 'Surgical removal'],
    precautions: ['Avoid sharing socks/shoes', 'Cover plantar warts when swimming', 'Do not pick at warts', 'Treat early to prevent spread'],
    specialists: ['Dermatologist', 'General Practitioner'],
    recurrenceRisk: 'Medium',
    contagious: true,
  },
  hsv: {
    name: 'Herpes Simplex',
    icd10: 'B00.9',
    category: 'Infectious',
    severity: 'Moderate',
    urgency: 'Within 1 week',
    description: 'Viral infection caused by herpes simplex virus (HSV-1 or HSV-2). Causes recurrent clusters of blisters/sores on lips/face (HSV-1) or genitals (HSV-2). Lifelong latent infection.',
    commonBodyParts: ['face', 'arm', 'leg', 'hand'],
    visualMarkers: ['Clustered vesicles/erosions', 'Perioral or perigenital location', 'Preceded by tingling/burning', 'Crusting after rupture', 'Recurrent episodes at same site'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Tingling/burning before outbreak', 'Clustered painful blisters', 'Flu-like symptoms (primary)', 'Recurrent episodes', 'Triggered by stress/sunlight/illness'],
    treatments: ['Antiviral medications (acyclovir, valacyclovir)', 'Suppressive therapy (daily antivirals for frequent recurrences)', 'Topical antiviral cream (acyclovir)', 'Pain management'],
    precautions: ['Avoid contact during active outbreak', 'Inform partners', 'Start antivirals at prodrome (tingling)', 'Sunscreen on lips (triggers)', 'Disclosure for sexual transmission'],
    specialists: ['General Practitioner', 'Dermatologist', 'Sexual Health Specialist'],
    recurrenceRisk: 'High',
    contagious: true,
  },
  fol: {
    name: 'Folliculitis',
    icd10: 'L73.9',
    category: 'Follicular',
    severity: 'Moderate',
    urgency: 'Within 1 month',
    description: 'Inflammation of hair follicles, most often due to bacterial infection. Appears as clusters of small pimples around hair follicles. Usually mild but can become deep (furuncles).',
    commonBodyParts: ['scalp', 'back', 'arm', 'leg', 'chest', 'face'],
    visualMarkers: ['Perifollicular pustules/papules', 'Clustered around hair follicles', 'Surrounding erythema', 'May have central hair shaft visible', 'Can coalesce into furuncles (boils)'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Clusters of small red bumps', 'Pus-filled sores', 'Itching and burning', 'Tenderness', 'Worsens after shaving or tight clothing'],
    treatments: ['Topical antibiotics (mupirocin)', 'Oral antibiotics (cefalexin for extensive)', 'Antifungal cream (fungal folliculitis)', 'Warm compresses', 'Improved hygiene/shaving technique'],
    precautions: ['Use clean razors', 'Avoid tight clothing', 'Keep skin clean and dry', 'Do not share towels', 'Treat swimming pools/hot tubs (pseudomonas folliculitis)'],
    specialists: ['General Practitioner', 'Dermatologist'],
    recurrenceRisk: 'Medium',
    contagious: false,
  },
  hid: {
    name: 'Hidradenitis Suppurativa',
    icd10: 'L73.2',
    category: 'Follicular',
    severity: 'High',
    urgency: 'Within 1 week',
    description: 'Chronic inflammatory skin disease causing painful nodules, abscesses, and tunnels (sinus tracts) in skin folds. Often delayed diagnosis. Significantly impacts quality of life.',
    commonBodyParts: ['arm', 'chest', 'leg', 'abdomen'],
    visualMarkers: ['Deep painful nodules in skin folds', 'Recurring abscesses', 'Sinus tracts (tunnels under skin)', 'Scarring and skin changes', 'Malodorous discharge'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Painful deep nodules in armpits/groin/buttocks', 'Recurring abscesses', 'Pus discharge', 'Scarring', 'Severe pain with movement'],
    treatments: ['Topical clindamycin', 'Oral antibiotics (tetracyclines, rifampicin + clindamycin)', 'Anti-androgens (spironolactone in women)', 'Biologics (adalimumab — FDA approved)', 'Surgical unroofing/wide excision'],
    precautions: ['Weight management', 'Smoking cessation (major trigger)', 'Loose breathable clothing', 'Gentle hygiene', 'Support groups for mental health'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'High',
    contagious: false,
  },

  // ─── TIER 6: PIGMENTATION DISORDERS ──────────────────────────────────────
  vit: {
    name: 'Vitiligo',
    icd10: 'L80',
    category: 'Pigmentation',
    severity: 'Moderate',
    urgency: 'Within 1 month',
    description: 'Autoimmune skin disease causing loss of melanocytes, resulting in white depigmented patches. Affects all races but most visible in darker skin types. Can affect any body area.',
    commonBodyParts: ['face', 'hand', 'arm', 'leg', 'scalp'],
    visualMarkers: ['Chalk-white depigmented patches', 'Sharp well-defined borders', 'Symmetrical distribution', 'Most visible under Wood\'s lamp', 'Koebner phenomenon (new patches at trauma sites)'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['White patches on skin', 'Premature whitening of hair', 'Loss of colour inside mouth', 'Change in eye color', 'Psychological impact'],
    treatments: ['Topical corticosteroids', 'Topical calcineurin inhibitors (tacrolimus)', 'Narrow-band UVB phototherapy', 'JAK inhibitors (ruxolitinib — topical)', 'Transplant procedures (for stable vitiligo)'],
    precautions: ['High SPF sunscreen on white patches (no melanin protection)', 'Psychological support', 'Evaluate for associated autoimmune conditions (thyroid)', 'Camouflage makeup for cosmetic concern'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'High',
    contagious: false,
  },
  mel_hyp: {
    name: 'Melasma',
    icd10: 'L81.1',
    category: 'Pigmentation',
    severity: 'Moderate',
    urgency: 'Routine',
    description: 'Acquired hyperpigmentation presenting as symmetric brown patches on sun-exposed skin, particularly the face. Common in women, especially pregnant women or those on oral contraceptives.',
    commonBodyParts: ['face', 'neck'],
    visualMarkers: ['Symmetric brown patches on cheeks/forehead/upper lip', 'Well-defined borders', 'Worsens with sun exposure', 'Post-inflammatory exacerbations', 'Multiple shades of brown'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Brown pigmentation on face', 'Worse in summer', 'Cosmetic distress', 'Symmetric pattern'],
    treatments: ['Triple combination cream (hydroquinone + tretinoin + corticosteroid)', 'Azelaic acid', 'Chemical peels', 'Sun protection (essential)', 'Tranexamic acid (oral/topical)'],
    precautions: ['Strict sun protection is cornerstone of treatment', 'Avoid or change oral contraceptives', 'Mineral sunscreen (tinted)', 'Avoid heat triggers (hot showers, exercise)'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'High',
    contagious: false,
  },
  an: {
    name: 'Acanthosis Nigricans',
    icd10: 'L83',
    category: 'Pigmentation',
    severity: 'Moderate',
    urgency: 'Within 1 month',
    description: 'Dark, velvety hyperpigmentation in body folds and creases. Associated with insulin resistance, obesity, and rarely malignancy. A marker of metabolic dysfunction.',
    commonBodyParts: ['neck', 'arm', 'abdomen'],
    visualMarkers: ['Dark velvety thickening of skin', 'Located in neck, axillae, groin', 'Hyperpigmented skin folds', 'Skin tags may accompany', 'Usually bilateral and symmetric'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Dark velvety skin in body folds', 'Skin tag clusters', 'Usually no symptoms', 'Occasionally itching'],
    treatments: ['Address underlying cause (weight loss, diabetes management)', 'Topical retinoids', 'Topical keratolytics', 'Chemical exfoliants', 'Screen for malignancy (rapid onset in adults)'],
    precautions: ['Blood glucose screening (diabetes risk)', 'Evaluate for PCOS in women', 'Rule out malignancy (sudden extensive onset)', 'Weight management'],
    specialists: ['Dermatologist', 'Endocrinologist'],
    recurrenceRisk: 'High',
    contagious: false,
  },
  pih: {
    name: 'Post-Inflammatory Hyperpigmentation',
    icd10: 'L81.0',
    category: 'Pigmentation',
    severity: 'Low',
    urgency: 'Routine',
    description: 'Flat dark marks left after skin inflammation or injury has healed. Very common in darker skin types. Caused by excess melanin production during healing.',
    commonBodyParts: ['face', 'arm', 'leg', 'back', 'chest'],
    visualMarkers: ['Flat dark macules at sites of prior inflammation', 'Corresponds to healed acne, eczema, or injury', 'Variable shades of brown/gray', 'Well-defined borders', 'No active inflammation'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Dark flat spots', 'Follow distribution of prior skin condition', 'More prominent in skin types IV-VI', 'Slow to fade (months to years)'],
    treatments: ['Topical hydroquinone', 'Retinoids (tretinoin)', 'Vitamin C serum', 'Chemical peels (AHA/BHA)', 'Strict sun protection to prevent worsening'],
    precautions: ['Treat underlying condition promptly (acne, eczema)', 'No picking or scratching', 'Daily SPF 30+ sunscreen essential', 'Patient education on timeline (may take many months)'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'High',
    contagious: false,
  },

  // ─── TIER 7: VASCULAR ─────────────────────────────────────────────────────
  vasc: {
    name: 'Vascular Lesion (Hemangioma / Angioma)',
    icd10: 'D18.01',
    category: 'Vascular',
    severity: 'Low',
    urgency: 'Routine',
    description: 'Benign vascular abnormalities appearing as red or purple marks. Include cherry angiomas (common in adults 40+), spider angiomas, port-wine stains, and infantile hemangiomas.',
    commonBodyParts: ['chest', 'back', 'arm', 'leg', 'face'],
    visualMarkers: ['Bright red papules or patches', 'Blanches with pressure', 'Superficial blood vessels visible', 'Cherry red dome (cherry angioma)', 'Central arteriole with radiating vessels (spider angioma)'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Red, blue, or purple spots on skin', 'Painless', 'May bleed if traumatized', 'No other symptoms'],
    treatments: ['No treatment needed (benign)', 'Laser treatment (cosmetic)', 'Electrocautery', 'Cryotherapy'],
    precautions: ['Consult doctor if sudden appearance of many (liver disease)', 'No treatment required for benign lesions'],
    specialists: ['Dermatologist'],
    recurrenceRisk: 'Low',
    contagious: false,
  },
  pur: {
    name: 'Purpura',
    icd10: 'D69.2',
    category: 'Vascular',
    severity: 'High',
    urgency: 'Immediate',
    description: 'Non-blanching red-purple discoloration caused by bleeding under the skin. Can indicate serious conditions including vasculitis, blood disorders, or meningococcemia.',
    commonBodyParts: ['leg', 'arm', 'chest', 'abdomen'],
    visualMarkers: ['Purple or red spots that do NOT blanch with pressure', 'Petechiae (<3mm)', 'Purpuric macules (3mm-1cm)', 'Ecchymosis (>1cm)', 'May have other systemic symptoms'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Purple-red non-blanching spots', 'May have fever (concerning)', 'Joint pain', 'Abdominal pain', 'Fatigue'],
    treatments: ['Treatment depends on underlying cause', 'Urgent medical evaluation required', 'Vasculitis: corticosteroids', 'Thrombocytopenia: platelet transfusion', 'Meningococcemia: urgent IV antibiotics'],
    precautions: ['URGENT — non-blanching rash with fever may indicate meningitis', 'Do the glass test (press glass on skin — if doesn\'t fade, seek emergency care)', 'Do not wait — seek immediate medical attention'],
    specialists: ['Emergency Physician', 'Haematologist', 'Rheumatologist'],
    recurrenceRisk: 'Medium',
    contagious: false,
  },
  cap: {
    name: 'Capillary Malformation (Port-Wine Stain)',
    icd10: 'Q82.5',
    category: 'Vascular',
    severity: 'Moderate',
    urgency: 'Routine',
    description: 'Congenital vascular birthmark caused by abnormal capillary development. Persists and darkens with age. May be associated with Sturge-Weber syndrome (facial lesions involving eye/brain).',
    commonBodyParts: ['face', 'neck', 'arm', 'leg', 'chest'],
    visualMarkers: ['Flat pink-red-purple birthmark', 'Present from birth', 'Darkens and thickens with age', 'Does not blanch completely', 'Unilateral distribution common'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['Pink-red patch present from birth', 'No symptoms', 'Darkens with age', 'Cosmetic concern'],
    treatments: ['Pulsed dye laser (treatment of choice)', 'Multiple laser sessions required', 'Evaluate for Sturge-Weber syndrome (facial lesions)', 'Photography documentation'],
    precautions: ['Evaluate for Sturge-Weber syndrome (ophthalmology + neurology)', 'Sunscreen to prevent darkening', 'Start laser treatment early for best results'],
    specialists: ['Dermatologist', 'Ophthalmologist (if near eye)', 'Neurologist (Sturge-Weber)'],
    recurrenceRisk: 'Low',
    contagious: false,
  },

  // ─── TIER 9: HEALTHY ──────────────────────────────────────────────────────
  healthy: {
    name: 'Healthy Skin',
    icd10: 'Z00.0',
    category: 'Healthy',
    severity: 'None',
    urgency: 'No action needed',
    description: 'No significant skin disease detected in the analyzed area. The skin shows normal texture, even pigmentation, and no concerning lesion morphology.',
    commonBodyParts: ['face', 'arm', 'hand', 'back', 'leg', 'foot', 'chest', 'abdomen', 'scalp', 'eye', 'neck', 'other'],
    visualMarkers: ['Normal skin texture', 'Even pigmentation', 'No lesions or abnormal growths', 'Smooth surface', 'Natural skin tone'],
    abcde: { asymmetry: false, border: false, color: false, diameter: false },
    symptoms: ['No symptoms'],
    treatments: ['Regular moisturizing', 'Daily sunscreen SPF30+', 'Healthy diet and hydration', 'Annual skin check'],
    precautions: ['Monthly self skin examination', 'Annual dermatology screening (if risk factors)', 'Sun protection year-round', 'Stay hydrated'],
    specialists: [],
    recurrenceRisk: 'None',
    contagious: false,
  },
}

// ─── BODY PART TO DISEASE MAPPING ─────────────────────────────────────────
export const BODY_DISEASE_MAP: Record<string, string[] | 'all'> = {
  face:    ['mel', 'bcc', 'ros', 'acne', 'mel_hyp', 'lu', 'lm', 'akiec', 'vit', 'dc', 'imp', 'hsv', 'mc', 'mcc', 'sk', 'nv'],
  arm:     ['mel', 'nv', 'akiec', 'bcc', 'df', 'vasc', 'ec', 'pso', 'vit', 'gr', 'hzv', 'tca', 'scc', 'pih'],
  hand:    ['ec', 'pso', 'tca', 'scb', 'vr', 'vasc', 'df', 'imp', 'scc', 'gr', 'hsv', 'pih', 'an'],
  back:    ['mel', 'nv', 'bkl', 'bcc', 'akiec', 'df', 'pso', 'fol', 'ep', 'mcc', 'vasc', 'hzv'],
  leg:     ['mel', 'nv', 'df', 'vasc', 'pur', 'cap', 'ec', 'cel', 'tca', 'pso', 'pih', 'vr'],
  foot:    ['tca', 'vr', 'mel', 'ec', 'pso', 'scb', 'cel', 'pih'],
  chest:   ['bkl', 'nv', 'gr', 'ec', 'pso', 'mel', 'vasc', 'fol', 'hzv', 'acne', 'ep'],
  abdomen: ['bkl', 'ep', 'lip', 'nv', 'hzv', 'gr', 'an', 'pso', 'mel', 'pur'],
  scalp:   ['pso', 'bkl', 'mel', 'scc', 'fol', 'tca', 'lm', 'akiec'],
  eye:     ['bcc', 'mel', 'mc', 'dc', 'lm', 'mcc'],
  ear:     ['bcc', 'scc', 'mel', 'akiec', 'ep', 'mcc'],
  neck:    ['bkl', 'nv', 'mc', 'an', 'bcc', 'mel', 'akiec', 'lm', 'lu', 'vasc'],
  other:   'all',
}

// ─── BODY PART DEFINITIONS ─────────────────────────────────────────────────
export interface BodyPartInfo {
  id: string
  label: string
  icon: string  // lucide icon name key — mapped to component in UI
  hint: string
  overlayShape: 'oval' | 'rectangle-tall' | 'square' | 'circle'
  facingMode: 'user' | 'environment'
}

export const BODY_PARTS: BodyPartInfo[] = [
  { id: 'face',    label: 'Face',           icon: 'face',    hint: 'Rosacea, Acne, Melasma, BCC, Melanoma',        overlayShape: 'oval',           facingMode: 'user' },
  { id: 'arm',     label: 'Arm',            icon: 'arm',     hint: 'Melanoma, Moles, Eczema, Psoriasis',           overlayShape: 'rectangle-tall', facingMode: 'environment' },
  { id: 'hand',    label: 'Hand / Fingers', icon: 'hand',    hint: 'Warts, Eczema, Psoriasis, Scabies',            overlayShape: 'square',         facingMode: 'environment' },
  { id: 'back',    label: 'Back',           icon: 'back',    hint: 'Melanoma, Moles, Seborrheic Keratosis',         overlayShape: 'circle',         facingMode: 'environment' },
  { id: 'leg',     label: 'Leg',            icon: 'leg',     hint: 'Vascular Lesions, Cellulitis, Eczema',          overlayShape: 'rectangle-tall', facingMode: 'environment' },
  { id: 'foot',    label: 'Foot / Sole',    icon: 'foot',    hint: 'Tinea, Warts, Melanoma',                       overlayShape: 'oval',           facingMode: 'environment' },
  { id: 'chest',   label: 'Chest',          icon: 'chest',   hint: 'Moles, Eczema, Psoriasis, Folliculitis',        overlayShape: 'circle',         facingMode: 'environment' },
  { id: 'abdomen', label: 'Abdomen',        icon: 'abdomen', hint: 'Cysts, Lipoma, Shingles, Moles',                overlayShape: 'circle',         facingMode: 'environment' },
  { id: 'scalp',   label: 'Scalp / Head',   icon: 'scalp',   hint: 'Psoriasis, Tinea, Melanoma',                   overlayShape: 'circle',         facingMode: 'environment' },
  { id: 'eye',     label: 'Eye Area',       icon: 'eye',     hint: 'BCC, Melanoma, Molluscum',                      overlayShape: 'oval',           facingMode: 'user' },
  { id: 'neck',    label: 'Neck',           icon: 'neck',    hint: 'Seborrheic Keratosis, Moles, BCC',              overlayShape: 'oval',           facingMode: 'user' },
  { id: 'other',   label: 'Other',          icon: 'other',   hint: 'All 40+ conditions will be checked',            overlayShape: 'circle',         facingMode: 'environment' },
]
